SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS SA SALT 'cd09c0bea30e6a02' HASH 'a52ffb2734f2f7873b2fdf1e8553afc154d6f0184ce6a1adf7c1bbce2b37bd16' ADMIN;            
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 7;        
CREATE MEMORY TABLE PUBLIC.ACCOUNT(
    ACCOUNTID INTEGER NOT NULL,
    ADDRESS VARCHAR(255),
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    IS_ADMIN BOOLEAN NOT NULL,
    IS_SUSPENDED BOOLEAN NOT NULL,
    LAST_NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PICKUP_TIME VARCHAR(255),
    REQUEST_SUSPEND BOOLEAN NOT NULL,
    SUSPENSION_APPROVED BOOLEAN NOT NULL,
    USER_NAME VARCHAR(255)
);        
ALTER TABLE PUBLIC.ACCOUNT ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(ACCOUNTID);          
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT;  
INSERT INTO PUBLIC.ACCOUNT(ACCOUNTID, ADDRESS, EMAIL, FIRST_NAME, IS_ADMIN, IS_SUSPENDED, LAST_NAME, PASSWORD, PICKUP_TIME, REQUEST_SUSPEND, SUSPENSION_APPROVED, USER_NAME) VALUES
(1, '123 Fake Street', 'aidenchiavatti@gmail.com', 'John', FALSE, FALSE, 'Doe', '$2a$10$EznwKP7zTJYyFeEgXulgc.sDdsZrXYibGEhBM5EK2YQ.28L8O8vry', 'Monday, 12 AM', FALSE, FALSE, 'user'),
(2, NULL, NULL, 'Super', TRUE, FALSE, 'User', '$2a$10$1/J5QRdgO5bSUxoLFNTzm.nbKsnVx9Th09or0TDKXPtZyNG6CiWwG', 'Pickup time not set yet', FALSE, FALSE, 'admin');   
CREATE MEMORY TABLE PUBLIC.BILL(
    BILLID INTEGER NOT NULL,
    DUE_DATE TIMESTAMP,
    TOTAL DOUBLE NOT NULL,
    ACCOUNT_ACCOUNTID INTEGER,
    PAYMENT_PAYMENTID BIGINT
);
ALTER TABLE PUBLIC.BILL ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(BILLID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.BILL;     
INSERT INTO PUBLIC.BILL(BILLID, DUE_DATE, TOTAL, ACCOUNT_ACCOUNTID, PAYMENT_PAYMENTID) VALUES
(3, TIMESTAMP '2018-01-01 22:11:07.364', 20.0, 1, NULL),
(4, TIMESTAMP '2018-12-30 22:11:07.365', 20.0, 1, NULL);
CREATE MEMORY TABLE PUBLIC.BILL_DISPUTES(
    BILL_BILLID INTEGER NOT NULL,
    DISPUTES_DISPUTEID INTEGER NOT NULL
);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BILL_DISPUTES;            
CREATE MEMORY TABLE PUBLIC.COMPLAINT(
    COMPLAINTID INTEGER NOT NULL,
    COMPLAINT VARCHAR(255),
    RESPONSE VARCHAR(255),
    VIEWED BOOLEAN NOT NULL
);  
ALTER TABLE PUBLIC.COMPLAINT ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(COMPLAINTID);      
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.COMPLAINT;
INSERT INTO PUBLIC.COMPLAINT(COMPLAINTID, COMPLAINT, RESPONSE, VIEWED) VALUES
(5, 'i am mad', NULL, FALSE),
(6, 'I AM SO MAD!!', NULL, FALSE); 
CREATE MEMORY TABLE PUBLIC.DISPUTE(
    DISPUTEID INTEGER NOT NULL,
    DISPUTE VARCHAR(255),
    RESPONSE VARCHAR(255)
);     
ALTER TABLE PUBLIC.DISPUTE ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(DISPUTEID);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DISPUTE;  
CREATE MEMORY TABLE PUBLIC.PAYMENT(
    PAYMENTID BIGINT NOT NULL,
    DATE TIMESTAMP,
    PAYMENT_TOTAL DOUBLE NOT NULL,
    BILL_BILLID INTEGER
);           
ALTER TABLE PUBLIC.PAYMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(PAYMENTID);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PAYMENT;  
ALTER TABLE PUBLIC.BILL_DISPUTES ADD CONSTRAINT PUBLIC.UK_BQGPI607YD1CFDNCVVEX5W8K2 UNIQUE(DISPUTES_DISPUTEID);
ALTER TABLE PUBLIC.BILL ADD CONSTRAINT PUBLIC.FKCVX8PLBDJHUJCHUY1CH5UIHSN FOREIGN KEY(ACCOUNT_ACCOUNTID) REFERENCES PUBLIC.ACCOUNT(ACCOUNTID) NOCHECK;         
ALTER TABLE PUBLIC.BILL_DISPUTES ADD CONSTRAINT PUBLIC.FK806U7J3KWF5JW59RQHIPNQACG FOREIGN KEY(DISPUTES_DISPUTEID) REFERENCES PUBLIC.DISPUTE(DISPUTEID) NOCHECK;               
ALTER TABLE PUBLIC.BILL_DISPUTES ADD CONSTRAINT PUBLIC.FK71IBO5UEVHL57VPQVEF9MCMPR FOREIGN KEY(BILL_BILLID) REFERENCES PUBLIC.BILL(BILLID) NOCHECK;            
ALTER TABLE PUBLIC.BILL ADD CONSTRAINT PUBLIC.FK679XLAAK1PTB21DKQKH004F73 FOREIGN KEY(PAYMENT_PAYMENTID) REFERENCES PUBLIC.PAYMENT(PAYMENTID) NOCHECK;         
ALTER TABLE PUBLIC.PAYMENT ADD CONSTRAINT PUBLIC.FK352I8MNR7LK6IKN2P5YVS3CEF FOREIGN KEY(BILL_BILLID) REFERENCES PUBLIC.BILL(BILLID) NOCHECK;  
